name: 编译 immortalwrt-mt798x-6.6 (本地.config)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装编译依赖
        run: |
          sudo apt update -y
          sudo apt install -y build-essential cmake git libncurses-dev python3
          sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison bzip2 ccache cpio curl device-tree-compiler flex gawk gettext gcc-multilib g++-multilib libtool libltdl-dev libssl-dev libelf-dev zlib1g-dev

      - name: 克隆源码
        run: |
          git clone -b openwrt-24.10-6.6 --single-branch --filter=blob:none https://github.com/padavanonly/immortalwrt-mt798x-6.6 immortalwrt

      - name: 放入你的 .config 文件
        run: |
          cp -f .config immortalwrt/.config

      - name: 更新 feeds
        working-directory: ./immortalwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: 下载依赖包
        working-directory: ./immortalwrt
        run: make download -j$(nproc)

      - name: 开始编译固件
        working-directory: ./immortalwrt
        run: make -j$(nproc) V=s

      - name: 上传固件
        uses: actions/upload-artifact@v4
        with:
          name: immortalwrt-mt798x-firmware
          path: |
            immortalwrt/bin/targets/mediatek/mt7981/*
            immortalwrt/bin/targets/mediatek/mt7986/*
